name: CI-SFTP

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  Deploy_to_nimbl_ai_via_sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build --base=/employeeportal 
      - name: SFTP Deploy Core Page
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: kaissh02
          server: nimbl.ai
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # will put all file under this path
          local_path: ./dist/* # default is ./*
          # files will copy to under remote_path
          remote_path: /web/employeeportal
          # delete_remote_files: true
          
          # sftp args
          args: '-o ConnectTimeout=5'
      - name: SFTP Deploy .htaccess file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: kaissh02
          server: nimbl.ai
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # will put all file under this path
          local_path: ./public/.htaccess # default is ./*
          # files will copy to under remote_path
          remote_path: /web/employeeportal
          
          # sftp args
          args: '-o ConnectTimeout=5'